---
title: "Assign2"
author: "M. Vaz"
date: "Saturday, September 05, 2015"
output: html_document
---

# B. Programming in R

## B.1 Help
```{r}

# Getting information about a known function
?mean
help(mean)

# Searching for an in-built function
help.search("mean")
apropos("mean")

# Searching for "outside" functions 
RSiteSearch("violin",restrict=c("functions"))

```


## B.2 Assignment
```{r}

a = 2+3
a
b = a+a
a+a;a+b

```


## B.3 Data structures
### B.3.1 Vectors
```{r}

y = c(8.3,8.6,10.7,10.8,11,11,11.1,11.2,11.3,11.4)

# Sequences
1:4
4:1
-1:3
-(1:3)
seq(1,3,.2)
seq(1,3,length=7)
rep(1,3)
rep(1:3,2)
rep(1:3,each=2)

```

### B.3.2 Getting information about vectors
```{r}

sum(y)
mean(y)
max(y)
length(y)
summary(y)

names = c("Lizbeth","ChenLei")
names  

b = c(T,F)
b  

class(y)
class(b)

y>10
y>mean(y)
y==11
y!=11

# Algebra with vectors
a = 1:3
b = 4:6
a+b
a*b
a/b
a+1
a*2
1/a
a*1:2
a*c(1,2,1)
1:4*1:2
1:4*c(1,2,1,2)

```

### B.3.3 Extraction and missing values
```{r}

y[1]
y[1:3]
y[y>mean(y)]

a = c(5,3,6,NA)
a
is.na(a)
!is.na(a)
a[!is.na(a)]
na.exclude(a)
mean(a)
d = na.exclude(a)
mean(d)

```

### B.3.4 Matrices
```{r}

matrix(letters[1:4],ncol=2)
m = matrix(1:4,nrow=2)
m
m2 = matrix(1:4,nrow=2,byrow=T)
m2
i = diag(1,nrow=2)
i
minv = solve(m)
m%*%minv==i

# Extraction
m[1,2]
m[1,1:2]
m[,2]
m[,]

# Simple matrix algebra
n = matrix(0:3,nrow=2)
n
m*n
m%*%n
n%*%m
1:2%*%m
m%*%1:2

```

### B.3.5 Data frames
```{r}

dat = data.frame(species=c("S.altissima","S.rugosa","E.graminifolia","A. pilosus"),treatment = factor(c("Control","Water", "Control", "Water")), height = c(1.1,0.8, 0.9, 1), width = c(1, 1.7, 0.6, 0.2))
dat
dat[2,]
dat[3,4]
dat[dat[,2]=="Water",]
subset(dat,treatment=="Water")

```

## B.4
```{r}






```


## B.6
```{r}






```


## B.13
```{r}






```
